spring:
  datasource:
    driver_class_name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl_auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change_log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        profile_view:
          name: profile-view-channel
        search_appearance:
          name: search-appearance-channel

server:
  port: 8086

logging:
  level:
    root: info

project_service:
  host: localhost
  port: 8082
